// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMmIZUXthndLJuJ96eZJ2OcJE0MnESZMw',
    appId: '1:671001901355:web:593282a10c96a26e0b2d6e',
    messagingSenderId: '671001901355',
    projectId: 'sundusproject-a5c87',
    authDomain: 'sundusproject-a5c87.firebaseapp.com',
    databaseURL: 'https://sundusproject-a5c87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sundusproject-a5c87.appspot.com',
    measurementId: 'G-T9RL2801VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBxu6fDAlNkxV3W68VbNMNK7pHiDgrcg',
    appId: '1:671001901355:android:f5e9b4a2fa6da0590b2d6e',
    messagingSenderId: '671001901355',
    projectId: 'sundusproject-a5c87',
    databaseURL: 'https://sundusproject-a5c87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sundusproject-a5c87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35-WpW04AoB0-V2xvUw6fSG8UlIpWdsw',
    appId: '1:671001901355:ios:6414391956dc81fe0b2d6e',
    messagingSenderId: '671001901355',
    projectId: 'sundusproject-a5c87',
    databaseURL: 'https://sundusproject-a5c87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sundusproject-a5c87.appspot.com',
    iosBundleId: 'com.example.conect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB35-WpW04AoB0-V2xvUw6fSG8UlIpWdsw',
    appId: '1:671001901355:ios:5e1911aa4ed6b8070b2d6e',
    messagingSenderId: '671001901355',
    projectId: 'sundusproject-a5c87',
    databaseURL: 'https://sundusproject-a5c87-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sundusproject-a5c87.appspot.com',
    iosBundleId: 'com.example.conect.RunnerTests',
  );
}
